import path from "node:path"

import { Glob } from "bun"

// Scans web/next content code fences for the languages actually used and writes web/next/src/lib/shiki-languages.ts: a lazy grammar map so the runtime shiki bundle carries only these grammars instead of shiki's full ~250-grammar bundledLanguages. Every language is keyed by its id and aliases (as shiki does), so any fence token (bash, ts, ...) resolves. Runs in the web/next dev and build; the output is git-ignored and regenerated, so adding a code block in a new language just works.

const ROOT = path.resolve(import.meta.dir, "../..")
const CONTENT = path.join(ROOT, "web/next/content")
const OUT = path.join(ROOT, "web/next/src/lib/shiki-languages.ts")

// Plain/synthetic langs shiki renders without a grammar file; never emit an import for these.
const SPECIAL = new Set(["", "text", "txt", "plaintext", "plain", "ansi", "none"])

type LangInfo = { id: string; aliases?: string[] }

async function main() {
  const shikiPath = Bun.resolveSync("shiki", path.join(ROOT, "web/next"))
  const { bundledLanguagesInfo } = (await import(shikiPath)) as {
    bundledLanguagesInfo: LangInfo[]
  }

  const idOfToken = new Map<string, string>()
  const aliasesOfId = new Map<string, string[]>()
  for (const info of bundledLanguagesInfo) {
    idOfToken.set(info.id, info.id)
    aliasesOfId.set(info.id, info.aliases ?? [])
    for (const alias of info.aliases ?? []) idOfToken.set(alias, info.id)
  }

  // Opening fence with a language token, at line start (optionally indented); closing fences carry no token and never match.
  const fence = /^[ \t]*(?:`{3,}|~{3,})([A-Za-z][\w#+.-]*)/gm
  const usedIds = new Set<string>()
  const unknown = new Set<string>()

  const glob = new Glob("**/*.{md,mdx}")
  for await (const file of glob.scan({ cwd: CONTENT })) {
    const text = await Bun.file(path.join(CONTENT, file)).text()
    for (const match of text.matchAll(fence)) {
      const token = (match[1] ?? "").toLowerCase()
      if (SPECIAL.has(token)) continue
      const id = idOfToken.get(token)
      if (id) usedIds.add(id)
      else unknown.add(token)
    }
  }

  if (unknown.size) {
    console.warn(
      `[shiki-langs] ignoring unknown code-fence language(s): ${[...unknown].sort().join(", ")}`,
    )
  }

  // Key each language by its id and aliases so any fence token resolves; every key maps to the one canonical grammar import.
  const entries: [string, string][] = []
  for (const id of usedIds) {
    for (const key of [id, ...(aliasesOfId.get(id) ?? [])]) entries.push([key, id])
  }
  entries.sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0))

  const ident = /^[A-Za-z_$][\w$]*$/
  const rows = entries
    .map(
      ([key, id]) =>
        `  ${ident.test(key) ? key : JSON.stringify(key)}: () => import("@shikijs/langs/${id}"),`,
    )
    .join("\n")

  const out =
    "// Generated by .github/scripts/shiki-langs.ts. Do not edit; run the script (or dev/build) to refresh.\n" +
    "// Lazy grammar map for the languages used in web/next content, so shiki bundles only these instead of its full set.\n\n" +
    `export const bundledLanguages = {\n${rows}\n}\n\n` +
    "export type BundledLanguage = keyof typeof bundledLanguages\n"

  let current = ""
  try {
    current = await Bun.file(OUT).text()
  } catch {
    current = ""
  }
  if (current === out) return
  await Bun.write(OUT, out)
  console.log(`[shiki-langs] wrote ${path.relative(ROOT, OUT)} (${usedIds.size} languages)`)
}

main()
